export const BEGIN_API_CALL = "BEGIN_API_CALL";

//-------------COMMON-------------//
//Professionals
export const GET_PROFESSIONALS_SUCCESS = "GET_PROFESSIONALS_SUCCESS";
export const GET_PROFESSIONAL_SUCCESS = "GET_PROFESSIONAL_SUCCESS";
export const CREATE_PROFESSIONALS_SUCCESS = "CREATE_PROFESSIONALS_SUCCESS";
export const UPDATE_PROFESSIONALS_SUCCESS = "UPDATE_PROFESSIONALS_SUCCESS";
export const INACTIVATE_PROFESSIONAL_SUCCESS =
  "INACTIVATE_PROFESSIONAL_SUCCESS";
export const ACTIVATE_PROFESSIONAL_SUCCESS = "ACTIVATE_PROFESSIONAL_SUCCESS";
export const SEARCH_PROFESSIONALS_SUCCESS = "SEARCH_PROFESSIONALS_SUCCESS";
//Areas
export const GET_AREAS_SUCCESS = "GET_AREAS_SUCCESS";
export const GET_PROFESSIONALS_BY_AREA_SUCCESS =
  "GET_PROFESSIONALS_BY_AREA_SUCCESS";

//-------------GENERAL-------------//
//Movements
export const GET_MOVEMENTS_BY_MONTH_SUCCESS = "GET_MOVEMENTS_BY_MONTH_SUCCESS";
//Concepts
export const GET_COMMON_CONCEPTS_SUCCESS = "GET_COMMON_CONCEPTS_SUCCESS";

//-------------PILATES-------------//
//Students
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const SEARCH_STUDENTS_SUCCESS = "SEARCH_STUDENTS_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const INACTIVATE_STUDENT_SUCCESS = "INACTIVATE_STUDENT_SUCCESS";
export const ACTIVATE_STUDENT_SUCCESS = "ACTIVATE_STUDENT_SUCCESS";
//Weekly Classes
export const GET_WEEKLY_CLASSES_SUCCESS = "GET_WEEKLY_CLASSES_SUCCESS";
export const GET_WEEKLY_CLASS_SUCCESS = "GET_WEEKLY_CLASS_SUCCESS";
export const CREATE_WEEKLY_CLASS_SUCCESS = "CREATE_WEEKLY_CLASS_SUCCESS";
export const UPDATE_WEEKLY_CLASS_SUCCESS = "UPDATE_WEEKLY_CLASS_SUCCESS";
export const ACTIVATE_WEEKLY_CLASS_SUCCESS = "ACTIVATE_WEEKLY_CLASS_SUCCESS";
export const INACTIVATE_WEEKLY_CLASS_SUCCESS =
  "INACTIVATE_WEEKLY_CLASS_SUCCESS";
export const SEARCH_WEEKLY_CLASSES_SUCCESS = "SEARCH_WEEKLY_CLASSES_SUCCESS";
//Classes
export const GET_CLASSES_BY_WEEK_SUCCESS = "GET_CLASSES_BY_WEEK_SUCCESS";
export const GET_CLASSES_BY_DATE_AND_HOUR_SUCCESS =
  "GET_CLASSES_BY_DATE_AND_HOUR_SUCCESS";
export const SAVE_CLASS_SUCCESS = "SAVE_CLASS_SUCCESS";
//Fees
export const GET_FEES_PER_MONTH_SUCCESS = "GET_FEES_PER_MONTH_SUCCESS";
export const CREATE_FEE_SUCCESS = "CREATE_FEE_SUCCESS";
export const UPDATE_FEE_SUCCESS = "UPDATE_FEE_SUCCESS";
//Months
export const GET_MONTHS_SUCCESS = "GET_MONTHS_SUCCESS";
//FeeTypes
export const GET_FEE_TYPES_SUCCESS = "GET_FEE_TYPES_SUCCESS";
export const GET_FEE_TYPE_SUCCESS = "GET_FEE_TYPE_SUCCESS";
//ProfessionalWorkDay
export const GET_SUGGESTED_PROFESSIONALS_SUCCESS =
  "GET_SUGGESTED_PROFESSIONALS_SUCCESS";
export const SAVE_PROFESSIONAL_WORK_DAY = "SAVE_PROFESSIONAL_WORK_DAY";
export const SAVE_PROFESSIONAL_WORK_DAYS = "SAVE_PROFESSIONAL_WORK_DAYS";
export const GET_PROFESSIONAL_WORK_DAY_BY_MONTH =
  "GET_PROFESSIONAL_WORK_DAY_BY_MONTH";
export const GET_PROFESSIONAL_WORK_DAY_BY_YEAR =
  "GET_PROFESSIONAL_WORK_DAY_BY_YEAR";
