export const GET_PROFESSIONALS_SUCCESS = "GET_PROFESSIONALS_SUCCESS";
export const CREATE_PROFESSIONALS_SUCCESS = "CREATE_PROFESSIONALS_SUCCESS";
export const UPDATE_PROFESSIONALS_SUCCESS = "UPDATE_PROFESSIONALS_SUCCESS";
export const INACTIVATE_PROFESSIONAL_SUCCESS =
  "INACTIVATE_PROFESSIONAL_SUCCESS";
export const ACTIVATE_PROFESSIONAL_SUCCESS = "ACTIVATE_PROFESSIONAL_SUCCESS";
