export const BEGIN_API_CALL = "BEGIN_API_CALL";

//-------------CONSULTINGROOM-------------//
//Professionals
export const GET_PROFESSIONALS_SUCCESS = "GET_PROFESSIONALS_SUCCESS";
export const CREATE_PROFESSIONALS_SUCCESS = "CREATE_PROFESSIONALS_SUCCESS";
export const UPDATE_PROFESSIONALS_SUCCESS = "UPDATE_PROFESSIONALS_SUCCESS";
export const INACTIVATE_PROFESSIONAL_SUCCESS =
  "INACTIVATE_PROFESSIONAL_SUCCESS";
export const ACTIVATE_PROFESSIONAL_SUCCESS = "ACTIVATE_PROFESSIONAL_SUCCESS";

//-------------PILATES-------------//
//Students
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const SEARCH_STUDENTS_SUCCESS = "SEARCH_STUDENTS_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const INACTIVATE_STUDENT_SUCCESS = "INACTIVATE_STUDENT_SUCCESS";
export const ACTIVATE_STUDENT_SUCCESS = "ACTIVATE_STUDENT_SUCCESS";
//Weekly Classes
export const GET_WEEKLY_CLASSES_SUCCESS = "GET_WEEKLY_CLASSES_SUCCESS";
export const GET_WEEKLY_CLASS_SUCCESS = "GET_WEEKLY_CLASS_SUCCESS";
export const CREATE_WEEKLY_CLASS_SUCCESS = "CREATE_WEEKLY_CLASS_SUCCESS";
export const UPDATE_WEEKLY_CLASS_SUCCESS = "UPDATE_WEEKLY_CLASS_SUCCESS";
//Fees
export const GET_FEES_PER_MONTH_SUCCESS = "GET_FEES_PER_MONTH_SUCCESS";
export const CREATE_FEE_SUCCESS = "CREATE_FEE_SUCCESS";
export const UPDATE_FEE_SUCCESS = "UPDATE_FEE_SUCCESS";
//Months
export const GET_MONTHS_SUCCESS = "GET_MONTHS_SUCCESS";
//FeeTypes
export const GET_FEE_TYPES_SUCCESS = "GET_FEE_TYPES_SUCCESS";
export const GET_FEE_TYPE_SUCCESS = "GET_FEE_TYPE_SUCCESS";
